version: "3.1"
services:
  checkout_app:
    image: checkout
    build: ./checkout/
    ports:
      - "8080:8080"
    depends_on:
      - checkout_postgres
  checkout_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=checkout
      - POSTGRES_PASSWORD=hackme123
    volumes:
      - checkout_pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  loms_app:
    image: loms
    build: ./loms/
    ports:
      - "8081:8081"
    depends_on:
      - loms_postgres
  loms_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=loms
      - POSTGRES_PASSWORD=hackme123
    volumes:
      - loms_pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"

volumes:
  checkout_pgdata:
  loms_pgdata:
