package domain

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/checkout/internal/domain.LOMSServiceClient -o ./zzz_loms_service_client.go -n LOMSServiceClientMock

import (
	"context"
	"route256/checkout/internal/models"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LOMSServiceClientMock implements LOMSServiceClient
type LOMSServiceClientMock struct {
	t minimock.Tester

	funcCreateOrder          func(ctx context.Context, user models.User, items []models.CartItem) (op1 *models.OrderID, err error)
	inspectFuncCreateOrder   func(ctx context.Context, user models.User, items []models.CartItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLOMSServiceClientMockCreateOrder

	funcStocks          func(ctx context.Context, sku models.SKU) (sa1 []models.Stock, err error)
	inspectFuncStocks   func(ctx context.Context, sku models.SKU)
	afterStocksCounter  uint64
	beforeStocksCounter uint64
	StocksMock          mLOMSServiceClientMockStocks
}

// NewLOMSServiceClientMock returns a mock for LOMSServiceClient
func NewLOMSServiceClientMock(t minimock.Tester) *LOMSServiceClientMock {
	m := &LOMSServiceClientMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLOMSServiceClientMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LOMSServiceClientMockCreateOrderParams{}

	m.StocksMock = mLOMSServiceClientMockStocks{mock: m}
	m.StocksMock.callArgs = []*LOMSServiceClientMockStocksParams{}

	return m
}

type mLOMSServiceClientMockCreateOrder struct {
	mock               *LOMSServiceClientMock
	defaultExpectation *LOMSServiceClientMockCreateOrderExpectation
	expectations       []*LOMSServiceClientMockCreateOrderExpectation

	callArgs []*LOMSServiceClientMockCreateOrderParams
	mutex    sync.RWMutex
}

// LOMSServiceClientMockCreateOrderExpectation specifies expectation struct of the LOMSServiceClient.CreateOrder
type LOMSServiceClientMockCreateOrderExpectation struct {
	mock    *LOMSServiceClientMock
	params  *LOMSServiceClientMockCreateOrderParams
	results *LOMSServiceClientMockCreateOrderResults
	Counter uint64
}

// LOMSServiceClientMockCreateOrderParams contains parameters of the LOMSServiceClient.CreateOrder
type LOMSServiceClientMockCreateOrderParams struct {
	ctx   context.Context
	user  models.User
	items []models.CartItem
}

// LOMSServiceClientMockCreateOrderResults contains results of the LOMSServiceClient.CreateOrder
type LOMSServiceClientMockCreateOrderResults struct {
	op1 *models.OrderID
	err error
}

// Expect sets up expected params for LOMSServiceClient.CreateOrder
func (mmCreateOrder *mLOMSServiceClientMockCreateOrder) Expect(ctx context.Context, user models.User, items []models.CartItem) *mLOMSServiceClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSServiceClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LOMSServiceClientMockCreateOrderExpectation{}
	}

	mmCreateOrder.defaultExpectation.params = &LOMSServiceClientMockCreateOrderParams{ctx, user, items}
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the LOMSServiceClient.CreateOrder
func (mmCreateOrder *mLOMSServiceClientMockCreateOrder) Inspect(f func(ctx context.Context, user models.User, items []models.CartItem)) *mLOMSServiceClientMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LOMSServiceClientMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by LOMSServiceClient.CreateOrder
func (mmCreateOrder *mLOMSServiceClientMockCreateOrder) Return(op1 *models.OrderID, err error) *LOMSServiceClientMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSServiceClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LOMSServiceClientMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LOMSServiceClientMockCreateOrderResults{op1, err}
	return mmCreateOrder.mock
}

// Set uses given function f to mock the LOMSServiceClient.CreateOrder method
func (mmCreateOrder *mLOMSServiceClientMockCreateOrder) Set(f func(ctx context.Context, user models.User, items []models.CartItem) (op1 *models.OrderID, err error)) *LOMSServiceClientMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the LOMSServiceClient.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the LOMSServiceClient.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	return mmCreateOrder.mock
}

// When sets expectation for the LOMSServiceClient.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLOMSServiceClientMockCreateOrder) When(ctx context.Context, user models.User, items []models.CartItem) *LOMSServiceClientMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSServiceClientMock.CreateOrder mock is already set by Set")
	}

	expectation := &LOMSServiceClientMockCreateOrderExpectation{
		mock:   mmCreateOrder.mock,
		params: &LOMSServiceClientMockCreateOrderParams{ctx, user, items},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up LOMSServiceClient.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LOMSServiceClientMockCreateOrderExpectation) Then(op1 *models.OrderID, err error) *LOMSServiceClientMock {
	e.results = &LOMSServiceClientMockCreateOrderResults{op1, err}
	return e.mock
}

// CreateOrder implements LOMSServiceClient
func (mmCreateOrder *LOMSServiceClientMock) CreateOrder(ctx context.Context, user models.User, items []models.CartItem) (op1 *models.OrderID, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, user, items)
	}

	mm_params := &LOMSServiceClientMockCreateOrderParams{ctx, user, items}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.op1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_got := LOMSServiceClientMockCreateOrderParams{ctx, user, items}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LOMSServiceClientMock.CreateOrder got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LOMSServiceClientMock.CreateOrder")
		}
		return (*mm_results).op1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, user, items)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LOMSServiceClientMock.CreateOrder. %v %v %v", ctx, user, items)
	return
}

// CreateOrderAfterCounter returns a count of finished LOMSServiceClientMock.CreateOrder invocations
func (mmCreateOrder *LOMSServiceClientMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LOMSServiceClientMock.CreateOrder invocations
func (mmCreateOrder *LOMSServiceClientMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LOMSServiceClientMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLOMSServiceClientMockCreateOrder) Calls() []*LOMSServiceClientMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LOMSServiceClientMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LOMSServiceClientMock) MinimockCreateOrderDone() bool {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LOMSServiceClientMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LOMSServiceClientMock.CreateOrder with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LOMSServiceClientMock.CreateOrder")
		} else {
			m.t.Errorf("Expected call to LOMSServiceClientMock.CreateOrder with params: %#v", *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		m.t.Error("Expected call to LOMSServiceClientMock.CreateOrder")
	}
}

type mLOMSServiceClientMockStocks struct {
	mock               *LOMSServiceClientMock
	defaultExpectation *LOMSServiceClientMockStocksExpectation
	expectations       []*LOMSServiceClientMockStocksExpectation

	callArgs []*LOMSServiceClientMockStocksParams
	mutex    sync.RWMutex
}

// LOMSServiceClientMockStocksExpectation specifies expectation struct of the LOMSServiceClient.Stocks
type LOMSServiceClientMockStocksExpectation struct {
	mock    *LOMSServiceClientMock
	params  *LOMSServiceClientMockStocksParams
	results *LOMSServiceClientMockStocksResults
	Counter uint64
}

// LOMSServiceClientMockStocksParams contains parameters of the LOMSServiceClient.Stocks
type LOMSServiceClientMockStocksParams struct {
	ctx context.Context
	sku models.SKU
}

// LOMSServiceClientMockStocksResults contains results of the LOMSServiceClient.Stocks
type LOMSServiceClientMockStocksResults struct {
	sa1 []models.Stock
	err error
}

// Expect sets up expected params for LOMSServiceClient.Stocks
func (mmStocks *mLOMSServiceClientMockStocks) Expect(ctx context.Context, sku models.SKU) *mLOMSServiceClientMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSServiceClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LOMSServiceClientMockStocksExpectation{}
	}

	mmStocks.defaultExpectation.params = &LOMSServiceClientMockStocksParams{ctx, sku}
	for _, e := range mmStocks.expectations {
		if minimock.Equal(e.params, mmStocks.defaultExpectation.params) {
			mmStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocks.defaultExpectation.params)
		}
	}

	return mmStocks
}

// Inspect accepts an inspector function that has same arguments as the LOMSServiceClient.Stocks
func (mmStocks *mLOMSServiceClientMockStocks) Inspect(f func(ctx context.Context, sku models.SKU)) *mLOMSServiceClientMockStocks {
	if mmStocks.mock.inspectFuncStocks != nil {
		mmStocks.mock.t.Fatalf("Inspect function is already set for LOMSServiceClientMock.Stocks")
	}

	mmStocks.mock.inspectFuncStocks = f

	return mmStocks
}

// Return sets up results that will be returned by LOMSServiceClient.Stocks
func (mmStocks *mLOMSServiceClientMockStocks) Return(sa1 []models.Stock, err error) *LOMSServiceClientMock {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSServiceClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LOMSServiceClientMockStocksExpectation{mock: mmStocks.mock}
	}
	mmStocks.defaultExpectation.results = &LOMSServiceClientMockStocksResults{sa1, err}
	return mmStocks.mock
}

// Set uses given function f to mock the LOMSServiceClient.Stocks method
func (mmStocks *mLOMSServiceClientMockStocks) Set(f func(ctx context.Context, sku models.SKU) (sa1 []models.Stock, err error)) *LOMSServiceClientMock {
	if mmStocks.defaultExpectation != nil {
		mmStocks.mock.t.Fatalf("Default expectation is already set for the LOMSServiceClient.Stocks method")
	}

	if len(mmStocks.expectations) > 0 {
		mmStocks.mock.t.Fatalf("Some expectations are already set for the LOMSServiceClient.Stocks method")
	}

	mmStocks.mock.funcStocks = f
	return mmStocks.mock
}

// When sets expectation for the LOMSServiceClient.Stocks which will trigger the result defined by the following
// Then helper
func (mmStocks *mLOMSServiceClientMockStocks) When(ctx context.Context, sku models.SKU) *LOMSServiceClientMockStocksExpectation {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSServiceClientMock.Stocks mock is already set by Set")
	}

	expectation := &LOMSServiceClientMockStocksExpectation{
		mock:   mmStocks.mock,
		params: &LOMSServiceClientMockStocksParams{ctx, sku},
	}
	mmStocks.expectations = append(mmStocks.expectations, expectation)
	return expectation
}

// Then sets up LOMSServiceClient.Stocks return parameters for the expectation previously defined by the When method
func (e *LOMSServiceClientMockStocksExpectation) Then(sa1 []models.Stock, err error) *LOMSServiceClientMock {
	e.results = &LOMSServiceClientMockStocksResults{sa1, err}
	return e.mock
}

// Stocks implements LOMSServiceClient
func (mmStocks *LOMSServiceClientMock) Stocks(ctx context.Context, sku models.SKU) (sa1 []models.Stock, err error) {
	mm_atomic.AddUint64(&mmStocks.beforeStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmStocks.afterStocksCounter, 1)

	if mmStocks.inspectFuncStocks != nil {
		mmStocks.inspectFuncStocks(ctx, sku)
	}

	mm_params := &LOMSServiceClientMockStocksParams{ctx, sku}

	// Record call args
	mmStocks.StocksMock.mutex.Lock()
	mmStocks.StocksMock.callArgs = append(mmStocks.StocksMock.callArgs, mm_params)
	mmStocks.StocksMock.mutex.Unlock()

	for _, e := range mmStocks.StocksMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmStocks.StocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocks.StocksMock.defaultExpectation.Counter, 1)
		mm_want := mmStocks.StocksMock.defaultExpectation.params
		mm_got := LOMSServiceClientMockStocksParams{ctx, sku}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocks.t.Errorf("LOMSServiceClientMock.Stocks got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocks.StocksMock.defaultExpectation.results
		if mm_results == nil {
			mmStocks.t.Fatal("No results are set for the LOMSServiceClientMock.Stocks")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmStocks.funcStocks != nil {
		return mmStocks.funcStocks(ctx, sku)
	}
	mmStocks.t.Fatalf("Unexpected call to LOMSServiceClientMock.Stocks. %v %v", ctx, sku)
	return
}

// StocksAfterCounter returns a count of finished LOMSServiceClientMock.Stocks invocations
func (mmStocks *LOMSServiceClientMock) StocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.afterStocksCounter)
}

// StocksBeforeCounter returns a count of LOMSServiceClientMock.Stocks invocations
func (mmStocks *LOMSServiceClientMock) StocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.beforeStocksCounter)
}

// Calls returns a list of arguments used in each call to LOMSServiceClientMock.Stocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocks *mLOMSServiceClientMockStocks) Calls() []*LOMSServiceClientMockStocksParams {
	mmStocks.mutex.RLock()

	argCopy := make([]*LOMSServiceClientMockStocksParams, len(mmStocks.callArgs))
	copy(argCopy, mmStocks.callArgs)

	mmStocks.mutex.RUnlock()

	return argCopy
}

// MinimockStocksDone returns true if the count of the Stocks invocations corresponds
// the number of defined expectations
func (m *LOMSServiceClientMock) MinimockStocksDone() bool {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	return true
}

// MinimockStocksInspect logs each unmet expectation
func (m *LOMSServiceClientMock) MinimockStocksInspect() {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LOMSServiceClientMock.Stocks with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		if m.StocksMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LOMSServiceClientMock.Stocks")
		} else {
			m.t.Errorf("Expected call to LOMSServiceClientMock.Stocks with params: %#v", *m.StocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		m.t.Error("Expected call to LOMSServiceClientMock.Stocks")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LOMSServiceClientMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateOrderInspect()

		m.MinimockStocksInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LOMSServiceClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LOMSServiceClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockStocksDone()
}
