global:
  scrape_interval: 2s
  scrape_timeout: 2s
  evaluation_interval: 1s # Evaluate rules

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: 
        - "localhost:9090"
  - job_name: "loms_app"
    static_configs:
      - targets: 
        - "loms_app:1000"
  - job_name: "checkout_app"
    static_configs:
      - targets:
        - "checkout_app:1000"
