server:
  address: ":8080"
postgres:
  dsn: postgres://user:hackme123@checkout_postgres:5432/checkout?sslmode=disable
externalServices:
  loms:
    url: loms:8081
  product:
    url: route256.pavl.uk:8082
    accessToken: test_token
